### ISSUE TITLE
crash: '/id-in?fu=1&rcn=4'

### ISSUE THREAD

**Issue by Spongman** [ankraft/ACME-oneM2M-CSE#41]
development branch only, works in master:

````
5190046203486207, permission: 32, selfPrivileges: False                                    SecurityManager.py:66
           DEBUG    5902 - Retrieve resource: acp3119621421175847417                                                                                                              Dispatcher.py:172
           DEBUG    5902 - Permission granted                                                                                                                                SecurityManager.py:118
           DEBUG    5902 - Retrieve resource: id-in                                                                                                                               Dispatcher.py:172
           DEBUG    5902 - <== Response (RSC: 2000):                                                                                                                              HttpServer.py:231
                    [<resources.FCNT_LA.FCNT_LA object at 0x7f923202fd00>, <resources.FCNT_OL.FCNT_OL object at 0x7f923202f3d0>]                                                                   
[12:09:04] ERROR    5902 - Exception on /id-in [GET]                                                                                                                                    app.py:2450
                    Traceback (most recent call last):                                                                                                                                             
                      File "/home/me/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app                                                                                  
                        response = self.full_dispatch_request()                                                                                                                                    
                      File "/home/me/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request                                                                     
                        rv = self.handle_user_exception(e)                                                                                                                                         
                      File "/home/me/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception                                                                     
                        reraise(exc_type, exc_value, tb)                                                                                                                                           
                      File "/home/me/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise                                                                                 
                        raise value                                                                                                                                                                
                      File "/home/me/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request                                                                     
                        rv = self.dispatch_request()                                                                                                                                               
                      File "/home/me/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request                                                                          
                        return self.view_functions[rule.endpoint](**req.view_args)                                                                                                                 
                      File "acme/HttpServer.py", line 110, in handleGET                                                                                                                            
                        return self._prepareResponse(request, resource, rc)                                                                                                                        
                      File "acme/HttpServer.py", line 232, in _prepareResponse                                                                                                                     
                        resp = make_response(r)                                                                                                                                                    
                      File "/home/me/.local/lib/python3.8/site-packages/flask/helpers.py", line 223, in make_response                                                                          
                        return current_app.make_response(args)                                                                                                                                     
                      File "/home/me/.local/lib/python3.8/site-packages/flask/app.py", line 2127, in make_response                                                                             
                        raise TypeError(                                                                                                                                                           
                    TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a                 
                    list.                                                                                                                                                                          
           DEBUG    5902 - "GET /id-in?fu=1&rcn=4 HTTP/1.1" - 500                                                                                                                 HttpServer.py:298
````

**Comment by ankraft** [comment]
Thanks for reporting. This should be solved.
Sorry, we merged a lot of changes today.
